#!/usr/bin/env bash


# Get the location of the "src" directory

source="${BASH_SOURCE}"

while [ -h "$source" ]; do
    source="$(readlink $source)"
done

src="$(dirname $source)/src/."


# Utility functions

status () {
    echo "web-template: $1"
}


# Set the destination directory

dest="."

if [ "$#" != "0" ]; then
    dest="$1"
fi


# If the destination is the current directory, make sure it is intentional

if [ "$dest" == "." ]; then
    read -p "web-template: copy files in the current directory? [y/N] " -n 1 -r

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        status "aborting"
        exit 1
    else
        echo
    fi
fi


# Create destination directory if needed

if [ ! -d "$dest" ]; then
    status "creating directory..."
    mkdir -p "$1"
fi


# Copy files

status "copying files..."
cp -r "$src" "$dest" && status "thunderbirds are go!"
